### ISSUE TITLE
git rev-parse's stdout ended before 64 characters were read

### ISSUE THREAD

**Issue by rvl** [NixOS/npm2nix#39]
Hi, npm2nix seems to be failing on the jsbn module, perhaps because it's a git repo type module, but I'm not sure.

``` shell
git clone git@github.com:NixOS/npm2nix.git
cd npm2nix
nix-shell
rm -rf ~/.npm
node --version > output.txt
git --version >> output.txt
node lib/command.js package.json node-packages-generated.nix >> output.txt 2>&1
```

Result: [output.txt](https://github.com/NixOS/npm2nix/files/233378/output.txt)

```
...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Error during fetch: Error fetching https://github.com/rynomad/jsbn.git from git: git rev-parse's stdout ended before 64 characters were read
```

Cheers

**Comment by rvl** [comment]
Strangely, this now works. I'm not sure what was going on before, but I could consistently get that error, for more than one project. Does npm2nix keep a cache of git repos or anything like that?

**Comment by chris-martin** [comment]
I consistently get this error in npm2nix from nixos-16.03.

```
Error during fetch: Error fetching git://github.com/NixOS/npm2nix.git#5.12.0 from git: git rev-parse's stdout ended before 64 characters were read
error: could not lock config file /run/user/1000/npm2nix-git-checkout-tabtab116424-23487-17snh8y/node-tabtab/.git/config: No such file or directory
fatal: Could not set 'remote.origin.fetch' to '+refs/heads/*:refs/remotes/origin/*'
error: could not lock config file /run/user/1000/npm2nix-git-checkout-pegjs116424-23487-32r9ec/pegjs/.git/config: No such file or directory
fatal: Could not set 'remote.origin.fetch' to '+refs/heads/*:refs/remotes/origin/*'
```

**Comment by chris-martin** [comment]
Is this a dupe of #36?

**Comment by chris-martin** [comment]
I switched from the npm2nix in 16.03 to nixos-unstable, and it seems to be working now.

**Comment by NicolasPetton** [comment]
I'm getting this issue again while running npm2nix on the latest nixos-unstable. @chris-martin have you done something to fix the issue?

**Comment by chris-martin** [comment]
No, I didn't do anything.

I don't think it matters, though. Even when it finishes running, it doesn't output anything. It seems that everything is blocked by #21.

**Comment by rvl** [comment]
I'm not sure if we're all seeing the same issue but I suspect the problem that I saw was timing related.

If my suspicion is correct then the awful nodejs async API is to blame.

I wish luck to the various people who are currently attempting to update npm2nix for the latest npm developments.

**Comment by NicolasPetton** [comment]
Rodney Lorrimar notifications@github.com writes:

> I'm not sure if we're all seeing the same issue but I suspect the
> problem that I saw was timing related.

I'll try to fix it, I need npm2nix to work.

**Comment by rvl** [comment]
Closing, using node2nix now.
