### ISSUE TITLE
Can't process git dependency by commit SHA

### ISSUE THREAD

**Issue by gfxmonk** [NixOS/npm2nix#9]
package.json:

    { "name": "testing"
      , "private" : true
      , "dependencies":
        { "fs-ext": "git://github.com/gfxmonk/node-fs-ext.git#4c77f466a42e92e3aee72a68d9fb37b0513cbd35"
        }
    }

Error output:

    # ./node_modules/.bin/npm2nix package.json out.nix
    Cloning into 'node-fs-ext'...
    remote: Counting objects: 176, done.
    remote: Compressing objects: 100% (9/9), done.
    remote: Total 176 (delta 1), reused 4 (delta 1)
    Receiving objects: 100% (176/176), 56.91 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (88/88), done.
    Checking connectivity... done.
    fatal: ambiguous argument 'origin/4c77f466a42e92e3aee72a68d9fb37b0513cbd35': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
    Error during fetch: Error fetching git://github.com/gfxmonk/node-fs-ext.git#4c77f466a42e92e3aee72a68d9fb37b0513cbd35 from git: git rev-parse exited with non-zero status code 128
    Note: checking out '4c77f466a42e92e3aee72a68d9fb37b0513cbd35'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b new_branch_name
    
    HEAD is now at 4c77f46... add fcntl to README.md

The error message seems to be coming from `git rev-parse`, while the warning about the detached HEAD state seems to be from a (successful) `git checkout` of the given commit.

I tried downgrading to version 5.6.0 of npm2nix, and that seems to work for the same package.json

**Comment by offlinehacker** [comment]
I think this is fixed in https://github.com/NixOS/npm2nix/commit/5d0753267cfb6e2cdb0503cf5d21471c077d68d0 are you still having the same problem?

**Comment by gfxmonk** [comment]
Nope - it works fine for me now. Thanks :)
